/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shogun;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Imrihil
 */
public class Initializator {

    public static void initializeDaimyo() throws IOException {
        Shogun.daimyos = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            Shogun.daimyos.add(new Daimyo(i, new Picture("/img/small/card/daimyo/daimyo" + Integer.toString(i) + ".png"), new Picture("/img/large/card/daimyo/daimyo" + Integer.toString(i) + ".png"), new Picture("/img/small/player/emblem/daimyo" + Integer.toString(i) + ".png"), new Picture("/img/large/player/emblem/daimyo" + Integer.toString(i) + ".png"), new Picture("/img/small/player/tray/daimyo" + Integer.toString(i) + "front.png"), new Picture("/img/large/player/tray/daimyo" + Integer.toString(i) + "front.png"), new Picture("/img/small/player/tray/daimyo" + Integer.toString(i) + "back.png"), new Picture("/img/large/player/tray/daimyo" + Integer.toString(i) + "back.png"), new Picture("/img/small/player/bigcounter/big" + Integer.toString(i) + ".png"), new Picture("/img/large/player/bigcounter/big" + Integer.toString(i) + ".png"), new Picture("/img/small/player/smallcounter/small" + Integer.toString(i) + ".png"), new Picture("/img/large/player/smallcounter/small" + Integer.toString(i) + ".png")));
        }
    }

    public static void initializeProvinces() throws IOException {
        //World
        Shogun.world = new HashMap<>();
        //Province
        Map<String, Province> provinces;
        //Buildings
        List<Place> buildings;
        //Neighbours
        Map<String, Province> neighbours;

        provinces = new HashMap<>();
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1770, 694));
        buildings.add(new Place(Building.EMPTY, 1762, 748));
        provinces.put("Mutsu", new Province("Mutsu", 4, 3, buildings, 1643, 638, 1742, 669, 218, 93, 1840, 715, 1900, 700, new Picture("/img/small/province/brown/Mutsu30.png"), new Picture("/img/large/province/brown/Mutsu30.png"), new Picture("/img/small/card/province/brown/Mutsu.png"), new Picture("/img/large/card/province/brown/Mutsu.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1532, 750));
        buildings.add(new Place(Building.EMPTY, 1606, 666));
        provinces.put("Echigo", new Province("Echigo", 5, 3, buildings, 1359, 644, 1502, 710, 143, 60, 1581, 749, 1684, 678, new Picture("/img/small/province/brown/Echigo30.png"), new Picture("/img/large/province/brown/Echigo30.png"), new Picture("/img/small/card/province/brown/Echigo.png"), new Picture("/img/large/card/province/brown/Echigo.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1738, 851));
        buildings.add(new Place(Building.EMPTY, 1776, 877));
        buildings.add(new Place(Building.EMPTY, 1830, 797));
        provinces.put("Shimotsuke", new Province("Shimotsuke", 6, 2, buildings, 1681, 763, 1713, 786, 135, 92, 1782, 825, 1734, 800, new Picture("/img/small/province/brown/Shimotsuke30.png"), new Picture("/img/large/province/brown/Shimotsuke30.png"), new Picture("/img/small/card/province/brown/Shimotsuke.png"), new Picture("/img/large/card/province/brown/Shimotsuke.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1902, 924));
        provinces.put("Hitachi", new Province("Hitachi", 3, 4, buildings, 1776, 803, 1829, 883, 90, 57, 1889, 863, 1846, 920, new Picture("/img/small/province/brown/Hitachi30.png"), new Picture("/img/large/province/brown/Hitachi30.png"), new Picture("/img/small/card/province/brown/Hitachi.png"), new Picture("/img/large/card/province/brown/Hitachi.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1612, 860));
        buildings.add(new Place(Building.EMPTY, 1608, 897));
        provinces.put("Kozuke", new Province("Kozuke", 3, 4, buildings, 1501, 772, 1553, 814, 135, 87, 1664, 863, 1555, 850, new Picture("/img/small/province/brown/Kozuke30.png"), new Picture("/img/large/province/brown/Kozuke30.png"), new Picture("/img/small/card/province/brown/Kozuke.png"), new Picture("/img/large/card/province/brown/Kozuke.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1404, 914));
        buildings.add(new Place(Building.EMPTY, 1457, 845));
        buildings.add(new Place(Building.EMPTY, 1384, 996));
        provinces.put("Shinano", new Province("Shinano", 6, 2, buildings, 1282, 788, 1346, 856, 133, 72, 1367, 948, 1400, 850, new Picture("/img/small/province/brown/Shinano30.png"), new Picture("/img/large/province/brown/Shinano30.png"), new Picture("/img/small/card/province/brown/Shinano.png"), new Picture("/img/large/card/province/brown/Shinano.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1246, 790));
        buildings.add(new Place(Building.EMPTY, 1289, 788));
        buildings.add(new Place(Building.EMPTY, 1224, 752));
        provinces.put("Etchu", new Province("Etchu", 7, 3, buildings, 1156, 741, 1276, 778, 85, 68, 1324, 799, 1202, 796, new Picture("/img/small/province/brown/Etchu30.png"), new Picture("/img/large/province/brown/Etchu30.png"), new Picture("/img/small/card/province/brown/Etchu.png"), new Picture("/img/large/card/province/brown/Etchu.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1049, 810));
        buildings.add(new Place(Building.EMPTY, 1120, 828));
        buildings.add(new Place(Building.EMPTY, 1089, 772));
        provinces.put("Kaga", new Province("Kaga", 4, 5, buildings, 1022, 743, 1074, 773, 83, 51, 1110, 799, 1084, 825, new Picture("/img/small/province/brown/Kaga30.png"), new Picture("/img/large/province/brown/Kaga30.png"), new Picture("/img/small/card/province/brown/Kaga.png"), new Picture("/img/large/card/province/brown/Kaga.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1221, 719));
        buildings.add(new Place(Building.EMPTY, 1186, 652));
        provinces.put("Noto", new Province("Noto", 5, 2, buildings, 1099, 643, 1138, 661, 79, 83, 1160, 729, 1249, 678, new Picture("/img/small/province/brown/Noto30.png"), new Picture("/img/large/province/brown/Noto30.png"), new Picture("/img/small/card/province/brown/Noto.png"), new Picture("/img/large/card/province/brown/Noto.png")));
        Shogun.world.put("brown", new Region(provinces));

        provinces = new HashMap<>();
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1802, 1284));
        buildings.add(new Place(Building.EMPTY, 1874, 1241));
        provinces.put("Awa-Boso", new Province("Awa-Boso", 3, 4, buildings, 1765, 1164, 1773, 1197, 111, 50, 1805, 1228, 1835, 1255, new Picture("/img/small/province/yellow/Awa-Boso30.png"), new Picture("/img/large/province/yellow/Awa-Boso30.png"), new Picture("/img/small/card/province/yellow/Awa-Boso.png"), new Picture("/img/large/card/province/yellow/Awa-Boso.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1857, 1142));
        buildings.add(new Place(Building.EMPTY, 1906, 1199));
        buildings.add(new Place(Building.EMPTY, 1888, 1114));
        provinces.put("Kazusa", new Province("Kazusa", 5, 3, buildings, 1810, 1073, 1827, 1144, 95, 30, 1896, 1144, 1928, 1108, new Picture("/img/small/province/yellow/Kazusa30.png"), new Picture("/img/large/province/yellow/Kazusa30.png"), new Picture("/img/small/card/province/yellow/Kazusa.png"), new Picture("/img/large/card/province/yellow/Kazusa.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1903, 1016));
        provinces.put("Shimosa", new Province("Shimosa", 5, 5, buildings, 1750, 907, 1831, 972, 102, 59, 1887, 1047, 1812, 962, new Picture("/img/small/province/yellow/Shimosa30.png"), new Picture("/img/large/province/yellow/Shimosa30.png"), new Picture("/img/small/card/province/yellow/Shimosa.png"), new Picture("/img/large/card/province/yellow/Shimosa.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1832, 1060));
        buildings.add(new Place(Building.EMPTY, 1636, 948));
        provinces.put("Musashi", new Province("Musashi", 6, 3, buildings, 1513, 891, 1703, 988, 102, 35, 1730, 975, 1769, 1040, new Picture("/img/small/province/yellow/Musashi30.png"), new Picture("/img/large/province/yellow/Musashi30.png"), new Picture("/img/small/card/province/yellow/Musashi.png"), new Picture("/img/large/card/province/yellow/Musashi.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1733, 1126));
        buildings.add(new Place(Building.EMPTY, 1780, 1102));
        buildings.add(new Place(Building.EMPTY, 1678, 1134));
        provinces.put("Sagami", new Province("Sagami", 3, 4, buildings, 1610, 970, 1629, 1036, 105, 49, 1692, 1092, 1664, 1019, new Picture("/img/small/province/yellow/Sagami30.png"), new Picture("/img/large/province/yellow/Sagami30.png"), new Picture("/img/small/card/province/yellow/Sagami.png"), new Picture("/img/large/card/province/yellow/Sagami.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1533, 996));
        provinces.put("Kai", new Province("Kai", 5, 3, buildings, 1443, 908, 1464, 934, 103, 57, 1565, 965, 1479, 964, new Picture("/img/small/province/yellow/Kai30.png"), new Picture("/img/large/province/yellow/Kai30.png"), new Picture("/img/small/card/province/yellow/Kai.png"), new Picture("/img/large/card/province/yellow/Kai.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1562, 1095));
        buildings.add(new Place(Building.EMPTY, 1527, 1104));
        provinces.put("Suruga", new Province("Suruga", 7, 3, buildings, 1469, 1004, 1491, 1027, 124, 79, 1554, 1048, 1617, 1113, new Picture("/img/small/province/yellow/Suruga30.png"), new Picture("/img/large/province/yellow/Suruga30.png"), new Picture("/img/small/card/province/yellow/Suruga.png"), new Picture("/img/large/card/province/yellow/Suruga.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1671, 1218));
        buildings.add(new Place(Building.EMPTY, 1605, 1268));
        buildings.add(new Place(Building.EMPTY, 1603, 1183));
        provinces.put("Izu", new Province("Izu", 6, 2, buildings, 1552, 1140, 1580, 1179, 80, 63, 1655, 1179, 1584, 1229, new Picture("/img/small/province/yellow/Izu30.png"), new Picture("/img/large/province/yellow/Izu30.png"), new Picture("/img/small/card/province/yellow/Izu.png"), new Picture("/img/large/card/province/yellow/Izu.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1448, 1153));
        buildings.add(new Place(Building.EMPTY, 1382, 1151));
        provinces.put("Totomi", new Province("Totomi", 6, 2, buildings, 1357, 981, 1411, 1036, 74, 126, 1450, 1078, 1478, 1137, new Picture("/img/small/province/yellow/Totomi30.png"), new Picture("/img/large/province/yellow/Totomi30.png"), new Picture("/img/small/card/province/yellow/Totomi.png"), new Picture("/img/large/card/province/yellow/Totomi.png")));
        Shogun.world.put("yellow", new Region(provinces));

        provinces = new HashMap<>();
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1299, 1138));
        provinces.put("Mikawa", new Province("Mikawa", 6, 3, buildings, 1232, 1029, 1260, 1045, 124, 75, 1355, 1060, 1284, 1057, new Picture("/img/small/province/red/Mikawa30.png"), new Picture("/img/large/province/red/Mikawa30.png"), new Picture("/img/small/card/province/red/Mikawa.png"), new Picture("/img/large/card/province/red/Mikawa.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1196, 1064));
        buildings.add(new Place(Building.EMPTY, 1187, 1013));
        provinces.put("Owari", new Province("Owari", 6, 2, buildings, 1125, 981, 1147, 1006, 80, 59, 1161, 1039, 1230, 1053, new Picture("/img/small/province/red/Owari30.png"), new Picture("/img/large/province/red/Owari30.png"), new Picture("/img/small/card/province/red/Owari.png"), new Picture("/img/large/card/province/red/Owari.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1159, 986));
        provinces.put("Mino", new Province("Mino", 3, 5, buildings, 1084, 864, 1091, 949, 195, 37, 1270, 989, 1171, 923, new Picture("/img/small/province/red/Mino30.png"), new Picture("/img/large/province/red/Mino30.png"), new Picture("/img/small/card/province/red/Mino.png"), new Picture("/img/large/card/province/red/Mino.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1268, 945));
        buildings.add(new Place(Building.EMPTY, 1253, 898));
        provinces.put("Hida", new Province("Hida", 4, 2, buildings, 1127, 808, 1203, 830, 72, 106, 1302, 892, 1180, 852, new Picture("/img/small/province/red/Hida30.png"), new Picture("/img/large/province/red/Hida30.png"), new Picture("/img/small/card/province/red/Hida.png"), new Picture("/img/large/card/province/red/Hida.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1000, 862));
        buildings.add(new Place(Building.EMPTY, 1013, 838));
        provinces.put("Echizen", new Province("Echizen", 4, 4, buildings, 968, 811, 1035, 863, 102, 66, 1076, 924, 1052, 868, new Picture("/img/small/province/red/Echizen30.png"), new Picture("/img/large/province/red/Echizen30.png"), new Picture("/img/small/card/province/red/Echizen.png"), new Picture("/img/large/card/province/red/Echizen.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 986, 1029));
        buildings.add(new Place(Building.EMPTY, 977, 1067));
        buildings.add(new Place(Building.EMPTY, 1085, 1023));
        provinces.put("Omi", new Province("Omi", 3, 2, buildings, 957, 957, 983, 985, 100, 108, 1047, 1067, 1024, 995, new Picture("/img/small/province/red/Omi30.png"), new Picture("/img/large/province/red/Omi30.png"), new Picture("/img/small/card/province/red/Omi.png"), new Picture("/img/large/card/province/red/Omi.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 953, 893));
        buildings.add(new Place(Building.EMPTY, 866, 823));
        provinces.put("Wakasa", new Province("Wakasa", 6, 2, buildings, 787, 813, 860, 884, 152, 55, 994, 924, 852, 884, new Picture("/img/small/province/red/Wakasa30.png"), new Picture("/img/large/province/red/Wakasa30.png"), new Picture("/img/small/card/province/red/Wakasa.png"), new Picture("/img/large/card/province/red/Wakasa.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 847, 967));
        provinces.put("Tamba", new Province("Tamba", 7, 2, buildings, 809, 923, 832, 956, 120, 57, 935, 1005, 878, 1002, new Picture("/img/small/province/red/Tamba30.png"), new Picture("/img/large/province/red/Tamba30.png"), new Picture("/img/small/card/province/red/Tamba.png"), new Picture("/img/large/card/province/red/Tamba.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 765, 1072));
        buildings.add(new Place(Building.EMPTY, 732, 1050));
        provinces.put("Harima", new Province("Harima", 4, 4, buildings, 677, 911, 687, 945, 115, 103, 784, 1014, 783, 966, new Picture("/img/small/province/red/Harima30.png"), new Picture("/img/large/province/red/Harima30.png"), new Picture("/img/small/card/province/red/Harima.png"), new Picture("/img/large/card/province/red/Harima.png")));
        Shogun.world.put("red", new Region(provinces));

        provinces = new HashMap<>();
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1158, 1160));
        provinces.put("Shima", new Province("Shima", 4, 3, buildings, 1108, 1140, 1126, 1173, 89, 44, 1203, 1200, 1145, 1210, new Picture("/img/small/province/purple/Shima30.png"), new Picture("/img/large/province/purple/Shima30.png"), new Picture("/img/small/card/province/purple/Shima.png"), new Picture("/img/large/card/province/purple/Shima.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 1126, 1124));
        buildings.add(new Place(Building.EMPTY, 1083, 1191));
        provinces.put("Ise", new Province("Ise", 5, 3, buildings, 1016, 1032, 1086, 1076, 47, 72, 1094, 1141, 1111, 1064, new Picture("/img/small/province/purple/Ise30.png"), new Picture("/img/large/province/purple/Ise30.png"), new Picture("/img/small/card/province/purple/Ise.png"), new Picture("/img/large/card/province/purple/Ise.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 913, 1281));
        buildings.add(new Place(Building.EMPTY, 833, 1167));
        provinces.put("Kii", new Province("Kii", 5, 4, buildings, 810, 1139, 824, 1154, 109, 85, 866, 1205, 1014, 1235, new Picture("/img/small/province/purple/Kii30.png"), new Picture("/img/large/province/purple/Kii30.png"), new Picture("/img/small/card/province/purple/Kii.png"), new Picture("/img/large/card/province/purple/Kii.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 984, 1155));
        buildings.add(new Place(Building.EMPTY, 1003, 1102));
        provinces.put("Yamato", new Province("Yamato", 5, 4, buildings, 928, 1079, 943, 1117, 92, 44, 970, 1179, 972, 1112, new Picture("/img/small/province/purple/Yamato30.png"), new Picture("/img/large/province/purple/Yamato30.png"), new Picture("/img/small/card/province/purple/Yamato.png"), new Picture("/img/large/card/province/purple/Yamato.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 891, 1106));
        provinces.put("Settsu", new Province("Settsu", 7, 3, buildings, 813, 1010, 828, 1044, 133, 41, 930, 1076, 844, 1047, new Picture("/img/small/province/purple/Settsu30.png"), new Picture("/img/large/province/purple/Settsu30.png"), new Picture("/img/small/card/province/purple/Settsu.png"), new Picture("/img/large/card/province/purple/Settsu.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 677, 1100));
        provinces.put("Sanuki", new Province("Sanuki", 6, 2, buildings, 582, 1081, 589, 1099, 115, 54, 690, 1132, 639, 1111, new Picture("/img/small/province/purple/Sanuki30.png"), new Picture("/img/large/province/purple/Sanuki30.png"), new Picture("/img/small/card/province/purple/Sanuki.png"), new Picture("/img/large/card/province/purple/Sanuki.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 734, 1204));
        buildings.add(new Place(Building.EMPTY, 646, 1181));
        provinces.put("Awa-Shikoku", new Province("Awa-Shikoku", 4, 2, buildings, 579, 1150, 636, 1173, 108, 86, 697, 1230, 641, 1216, new Picture("/img/small/province/purple/Awa-Shikoku30.png"), new Picture("/img/large/province/purple/Awa-Shikoku30.png"), new Picture("/img/small/card/province/purple/Awa-Shikoku.png"), new Picture("/img/large/card/province/purple/Awa-Shikoku.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 537, 1225));
        buildings.add(new Place(Building.EMPTY, 472, 1264));
        provinces.put("Tosa", new Province("Tosa", 6, 3, buildings, 368, 1163, 440, 1195, 159, 43, 448, 1223, 525, 1190, new Picture("/img/small/province/purple/Tosa30.png"), new Picture("/img/large/province/purple/Tosa30.png"), new Picture("/img/small/card/province/purple/Tosa.png"), new Picture("/img/large/card/province/purple/Tosa.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 382, 1150));
        buildings.add(new Place(Building.EMPTY, 396, 1187));
        buildings.add(new Place(Building.EMPTY, 483, 1100));
        provinces.put("Iyo", new Province("Iyo", 3, 4, buildings, 341, 1089, 428, 1112, 113, 54, 516, 1135, 430, 1163, new Picture("/img/small/province/purple/Iyo30.png"), new Picture("/img/large/province/purple/Iyo30.png"), new Picture("/img/small/card/province/purple/Iyo.png"), new Picture("/img/large/card/province/purple/Iyo.png")));
        Shogun.world.put("purple", new Region(provinces));

        provinces = new HashMap<>();
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 769, 845));
        provinces.put("Tajima", new Province("Tajima", 4, 4, buildings, 708, 826, 730, 870, 86, 48, 792, 900, 738, 855, new Picture("/img/small/province/green/Tajima30.png"), new Picture("/img/large/province/green/Tajima30.png"), new Picture("/img/small/card/province/green/Tajima.png"), new Picture("/img/large/card/province/green/Tajima.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 679, 834));
        buildings.add(new Place(Building.EMPTY, 486, 817));
        provinces.put("Hoki", new Province("Hoki", 6, 5, buildings, 460, 797, 494, 826, 219, 54, 532, 852, 636, 856, new Picture("/img/small/province/green/Hoki30.png"), new Picture("/img/large/province/green/Hoki30.png"), new Picture("/img/small/card/province/green/Hoki.png"), new Picture("/img/large/card/province/green/Hoki.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 634, 941));
        provinces.put("Mimasaka", new Province("Mimasaka", 7, 3, buildings, 540, 876, 574, 906, 119, 47, 596, 910, 667, 951, new Picture("/img/small/province/green/Mimasaka30.png"), new Picture("/img/large/province/green/Mimasaka30.png"), new Picture("/img/small/card/province/green/Mimasaka.png"), new Picture("/img/large/card/province/green/Mimasaka.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 620, 1054));
        provinces.put("Bizen", new Province("Bizen", 4, 2, buildings, 561, 959, 579, 984, 108, 68, 661, 1014, 602, 993, new Picture("/img/small/province/green/Bizen30.png"), new Picture("/img/large/province/green/Bizen30.png"), new Picture("/img/small/card/province/green/Bizen.png"), new Picture("/img/large/card/province/green/Bizen.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 528, 1018));
        buildings.add(new Place(Building.EMPTY, 550, 1059));
        provinces.put("Bitchu", new Province("Bitchu", 5, 3, buildings, 477, 901, 489, 939, 89, 115, 539, 942, 560, 1012, new Picture("/img/small/province/green/Bitchu30.png"), new Picture("/img/large/province/green/Bitchu30.png"), new Picture("/img/small/card/province/green/Bitchu.png"), new Picture("/img/large/card/province/green/Bitchu.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 415, 1059));
        buildings.add(new Place(Building.EMPTY, 473, 1070));
        provinces.put("Bingo", new Province("Bingo", 3, 4, buildings, 347, 917, 372, 929, 109, 101, 453, 1013, 438, 952, new Picture("/img/small/province/green/Bingo30.png"), new Picture("/img/large/province/green/Bingo30.png"), new Picture("/img/small/card/province/green/Bingo.png"), new Picture("/img/large/card/province/green/Bingo.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 396, 854));
        buildings.add(new Place(Building.EMPTY, 362, 846));
        buildings.add(new Place(Building.EMPTY, 431, 815));
        provinces.put("Izumo", new Province("Izumo", 3, 3, buildings, 331, 797, 368, 811, 97, 112, 442, 869, 365, 887, new Picture("/img/small/province/green/Izumo30.png"), new Picture("/img/large/province/green/Izumo30.png"), new Picture("/img/small/card/province/green/Izumo.png"), new Picture("/img/large/card/province/green/Izumo.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 266, 903));
        provinces.put("Iwami", new Province("Iwami", 7, 2, buildings, 215, 859, 249, 897, 107, 81, 325, 900, 322, 959, new Picture("/img/small/province/green/Iwami30.png"), new Picture("/img/large/province/green/Iwami30.png"), new Picture("/img/small/card/province/green/Iwami.png"), new Picture("/img/large/card/province/green/Iwami.png")));
        buildings = new ArrayList<>();
        buildings.add(new Place(Building.EMPTY, 333, 1061));
        buildings.add(new Place(Building.EMPTY, 260, 1060));
        provinces.put("Aki", new Province("Aki", 4, 3, buildings, 186, 965, 202, 992, 154, 63, 229, 999, 331, 1021, new Picture("/img/small/province/green/Aki30.png"), new Picture("/img/large/province/green/Aki30.png"), new Picture("/img/small/card/province/green/Aki.png"), new Picture("/img/large/card/province/green/Aki.png")));
        Shogun.world.put("green", new Region(provinces));

        neighbours = new HashMap<>();
        addProvince("Echigo", neighbours);
        addProvince("Kozuke", neighbours);
        addProvince("Shimotsuke", neighbours);
        addProvince("Hitachi", neighbours);
        Shogun.getProvince("Mutsu").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Mutsu", neighbours);
        addProvince("Shimotsuke", neighbours);
        addProvince("Shimosa", neighbours);
        Shogun.getProvince("Hitachi").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Kozuke", neighbours);
        addProvince("Mutsu", neighbours);
        addProvince("Hitachi", neighbours);
        addProvince("Shimosa", neighbours);
        Shogun.getProvince("Shimotsuke").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Shimotsuke", neighbours);
        addProvince("Mutsu", neighbours);
        addProvince("Echigo", neighbours);
        addProvince("Shinano", neighbours);
        addProvince("Musashi", neighbours);
        addProvince("Shimosa", neighbours);
        Shogun.getProvince("Kozuke").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Mutsu", neighbours);
        addProvince("Kozuke", neighbours);
        addProvince("Shinano", neighbours);
        addProvince("Etchu", neighbours);
        Shogun.getProvince("Echigo").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Kozuke", neighbours);
        addProvince("Echigo", neighbours);
        addProvince("Etchu", neighbours);
        addProvince("Hida", neighbours);
        addProvince("Mino", neighbours);
        addProvince("Mikawa", neighbours);
        addProvince("Totomi", neighbours);
        addProvince("Kai", neighbours);
        addProvince("Musashi", neighbours);
        Shogun.getProvince("Shinano").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Echigo", neighbours);
        addProvince("Shinano", neighbours);
        addProvince("Hida", neighbours);
        addProvince("Kaga", neighbours);
        addProvince("Noto", neighbours);
        Shogun.getProvince("Etchu").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Etchu", neighbours);
        addProvince("Kaga", neighbours);
        Shogun.getProvince("Noto").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Noto", neighbours);
        addProvince("Etchu", neighbours);
        addProvince("Hida", neighbours);
        addProvince("Echizen", neighbours);
        addProvince("Tajima", neighbours);
        Shogun.getProvince("Kaga").setNeighbour(neighbours);

        neighbours = new HashMap<>();
        addProvince("Kazusa", neighbours);
        addProvince("Izu", neighbours);
        Shogun.getProvince("Awa-Boso").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Awa-Boso", neighbours);
        addProvince("Shimosa", neighbours);
        Shogun.getProvince("Kazusa").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Kazusa", neighbours);
        addProvince("Musashi", neighbours);
        addProvince("Kozuke", neighbours);
        addProvince("Shimotsuke", neighbours);
        addProvince("Hitachi", neighbours);
        Shogun.getProvince("Shimosa").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Shimosa", neighbours);
        addProvince("Kozuke", neighbours);
        addProvince("Shinano", neighbours);
        addProvince("Kai", neighbours);
        addProvince("Sagami", neighbours);
        Shogun.getProvince("Musashi").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Musashi", neighbours);
        addProvince("Kai", neighbours);
        addProvince("Suruga", neighbours);
        addProvince("Izu", neighbours);
        Shogun.getProvince("Sagami").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Awa-Boso", neighbours);
        addProvince("Sagami", neighbours);
        addProvince("Suruga", neighbours);
        addProvince("Shima", neighbours);
        Shogun.getProvince("Izu").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Izu", neighbours);
        addProvince("Sagami", neighbours);
        addProvince("Kai", neighbours);
        addProvince("Totomi", neighbours);
        Shogun.getProvince("Suruga").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Totomi", neighbours);
        addProvince("Suruga", neighbours);
        addProvince("Sagami", neighbours);
        addProvince("Musashi", neighbours);
        addProvince("Shinano", neighbours);
        addProvince("Mikawa", neighbours);
        Shogun.getProvince("Kai").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Suruga", neighbours);
        addProvince("Kai", neighbours);
        addProvince("Shinano", neighbours);
        addProvince("Mikawa", neighbours);
        Shogun.getProvince("Totomi").setNeighbour(neighbours);

        neighbours = new HashMap<>();
        addProvince("Totomi", neighbours);
        addProvince("Shinano", neighbours);
        addProvince("Mino", neighbours);
        addProvince("Owari", neighbours);
        Shogun.getProvince("Mikawa").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Mikawa", neighbours);
        addProvince("Mino", neighbours);
        addProvince("Ise", neighbours);
        Shogun.getProvince("Owari").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Shinano", neighbours);
        addProvince("Hida", neighbours);
        addProvince("Echizen", neighbours);
        addProvince("Omi", neighbours);
        addProvince("Ise", neighbours);
        addProvince("Owari", neighbours);
        addProvince("Mikawa", neighbours);
        Shogun.getProvince("Mino").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Shinano", neighbours);
        addProvince("Etchu", neighbours);
        addProvince("Kaga", neighbours);
        addProvince("Echizen", neighbours);
        addProvince("Mino", neighbours);
        Shogun.getProvince("Hida").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Wakasa", neighbours);
        addProvince("Omi", neighbours);
        addProvince("Mino", neighbours);
        addProvince("Hida", neighbours);
        addProvince("Kaga", neighbours);
        Shogun.getProvince("Echizen").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Mino", neighbours);
        addProvince("Echizen", neighbours);
        addProvince("Wakasa", neighbours);
        addProvince("Tamba", neighbours);
        addProvince("Settsu", neighbours);
        addProvince("Yamato", neighbours);
        addProvince("Ise", neighbours);
        Shogun.getProvince("Omi").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Tajima", neighbours);
        addProvince("Tamba", neighbours);
        addProvince("Omi", neighbours);
        addProvince("Echizen", neighbours);
        Shogun.getProvince("Wakasa").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Tajima", neighbours);
        addProvince("Harima", neighbours);
        addProvince("Settsu", neighbours);
        addProvince("Omi", neighbours);
        addProvince("Wakasa", neighbours);
        Shogun.getProvince("Tamba").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Tajima", neighbours);
        addProvince("Hoki", neighbours);
        addProvince("Mimasaka", neighbours);
        addProvince("Bizen", neighbours);
        addProvince("Sanuki", neighbours);
        addProvince("Settsu", neighbours);
        addProvince("Tamba", neighbours);
        Shogun.getProvince("Harima").setNeighbour(neighbours);

        neighbours = new HashMap<>();
        addProvince("Izu", neighbours);
        addProvince("Ise", neighbours);
        Shogun.getProvince("Shima").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Owari", neighbours);
        addProvince("Mino", neighbours);
        addProvince("Omi", neighbours);
        addProvince("Yamato", neighbours);
        addProvince("Kii", neighbours);
        addProvince("Shima", neighbours);
        Shogun.getProvince("Ise").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Omi", neighbours);
        addProvince("Settsu", neighbours);
        addProvince("Kii", neighbours);
        addProvince("Ise", neighbours);
        Shogun.getProvince("Yamato").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Ise", neighbours);
        addProvince("Yamato", neighbours);
        addProvince("Settsu", neighbours);
        addProvince("Awa-Shikoku", neighbours);
        Shogun.getProvince("Kii").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Kii", neighbours);
        addProvince("Yamato", neighbours);
        addProvince("Omi", neighbours);
        addProvince("Tamba", neighbours);
        addProvince("Harima", neighbours);
        Shogun.getProvince("Settsu").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Harima", neighbours);
        addProvince("Iyo", neighbours);
        addProvince("Awa-Shikoku", neighbours);
        Shogun.getProvince("Sanuki").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Kii", neighbours);
        addProvince("Sanuki", neighbours);
        addProvince("Iyo", neighbours);
        addProvince("Tosa", neighbours);
        Shogun.getProvince("Awa-Shikoku").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Awa-Shikoku", neighbours);
        addProvince("Iyo", neighbours);
        Shogun.getProvince("Tosa").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Tosa", neighbours);
        addProvince("Awa-Shikoku", neighbours);
        addProvince("Sanuki", neighbours);
        addProvince("Aki", neighbours);
        Shogun.getProvince("Iyo").setNeighbour(neighbours);

        neighbours = new HashMap<>();
        addProvince("Kaga", neighbours);
        addProvince("Wakasa", neighbours);
        addProvince("Tamba", neighbours);
        addProvince("Harima", neighbours);
        addProvince("Hoki", neighbours);
        Shogun.getProvince("Tajima").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Tajima", neighbours);
        addProvince("Harima", neighbours);
        addProvince("Mimasaka", neighbours);
        addProvince("Bitchu", neighbours);
        addProvince("Bingo", neighbours);
        addProvince("Izumo", neighbours);
        Shogun.getProvince("Hoki").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Hoki", neighbours);
        addProvince("Bitchu", neighbours);
        addProvince("Bizen", neighbours);
        addProvince("Harima", neighbours);
        Shogun.getProvince("Mimasaka").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Harima", neighbours);
        addProvince("Mimasaka", neighbours);
        addProvince("Bitchu", neighbours);
        Shogun.getProvince("Bizen").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Bizen", neighbours);
        addProvince("Mimasaka", neighbours);
        addProvince("Hoki", neighbours);
        addProvince("Bingo", neighbours);
        Shogun.getProvince("Bitchu").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Bitchu", neighbours);
        addProvince("Hoki", neighbours);
        addProvince("Izumo", neighbours);
        addProvince("Iwami", neighbours);
        addProvince("Aki", neighbours);
        Shogun.getProvince("Bingo").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Hoki", neighbours);
        addProvince("Bingo", neighbours);
        addProvince("Iwami", neighbours);
        Shogun.getProvince("Izumo").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Izumo", neighbours);
        addProvince("Bingo", neighbours);
        addProvince("Aki", neighbours);
        Shogun.getProvince("Iwami").setNeighbour(neighbours);
        neighbours = new HashMap<>();
        addProvince("Iwami", neighbours);
        addProvince("Bingo", neighbours);
        addProvince("Iyo", neighbours);
        Shogun.getProvince("Aki").setNeighbour(neighbours);

        buildings = new ArrayList<>();
        neighbours = new HashMap<>();
        Shogun.provinceDrag = new Province("Drag", 0, 0, buildings, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null);
        Shogun.provinceDrag.setNeighbour(neighbours);
    }

    public static void initializeActions() throws IOException {
        Shogun.actions = new ArrayList<>();
        Shogun.actions.add(new Action0Castle());
        Shogun.actions.add(new Action1Temple());
        Shogun.actions.add(new Action2Theatre());
        Shogun.actions.add(new Action3Rice());
        Shogun.actions.add(new Action4Gold());
        Shogun.actions.add(new Action5Recruitment5());
        Shogun.actions.add(new Action6Recruitment3());
        Shogun.actions.add(new Action7Recruitment1());
        Shogun.actions.add(new Action8MoveA());
        Shogun.actions.add(new Action9MoveB());
        Shogun.actionBid = new ActionBid();
        Shogun.actionDrag = new ActionDrag();
    }

    public static void initializeEvents() throws IOException {
        Shogun.allEvents = new ArrayList<>();
        Shogun.allEvents.add(new Event("event0", new Picture("/img/small/card/event/event0.png"), new Picture("/img/large/card/event/event0.png"), 5, 1, 0, 0, false, 10, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event1", new Picture("/img/small/card/event/event1.png"), new Picture("/img/large/card/event/event1.png"), 7, 1, 0, 0, false, 10, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event2", new Picture("/img/small/card/event/event2.png"), new Picture("/img/large/card/event/event2.png"), 3, 0, 1, 0, false, 10, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event3", new Picture("/img/small/card/event/event3.png"), new Picture("/img/large/card/event/event3.png"), 2, 0, 0, 1, false, 10, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event4", new Picture("/img/small/card/event/event4.png"), new Picture("/img/large/card/event/event4.png"), 6, 0, 0, 1, false, 10, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event5", new Picture("/img/small/card/event/event5.png"), new Picture("/img/large/card/event/event5.png"), 3, 0, 0, 0, true, 10, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event6", new Picture("/img/small/card/event/event6.png"), new Picture("/img/large/card/event/event6.png"), 0, 0, 0, 0, false, 5, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event7", new Picture("/img/small/card/event/event7.png"), new Picture("/img/large/card/event/event7.png"), 2, 0, 0, 0, false, 10, 6, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event8", new Picture("/img/small/card/event/event8.png"), new Picture("/img/large/card/event/event8.png"), 4, 0, 0, 0, true, 10, 0, 10, 0, 5, 3));
        Shogun.allEvents.add(new Event("event9", new Picture("/img/small/card/event/event9.png"), new Picture("/img/large/card/event/event9.png"), 3, 0, 0, 0, false, 10, 0, 10, 4, 5, 3));
        Shogun.allEvents.add(new Event("event10", new Picture("/img/small/card/event/event10.png"), new Picture("/img/large/card/event/event10.png"), 4, 0, 0, 0, false, 10, 0, 3, 0, 5, 3));
        Shogun.allEvents.add(new Event("event11", new Picture("/img/small/card/event/event11.png"), new Picture("/img/large/card/event/event11.png"), 1, 0, 0, 0, false, 10, 0, 10, 0, 3, 2));
    }

    public static void initializeSpecials() throws IOException {
        Shogun.specials = new ArrayList<>();
        Shogun.specials.add(new Special("attack", new Picture("/img/small/card/special/special0.png"), new Picture("/img/large/card/special/special0.png"), new Picture("/img/small/card/special/special0h.png"), new Picture("/img/large/card/special/special0h.png"), 1, 0, 0, 0, 0));
        Shogun.specials.add(new Special("defence", new Picture("/img/small/card/special/special1.png"), new Picture("/img/large/card/special/special1.png"), new Picture("/img/small/card/special/special1h.png"), new Picture("/img/large/card/special/special1h.png"), 0, 1, 0, 0, 0));
        Shogun.specials.add(new Special("gold", new Picture("/img/small/card/special/special2.png"), new Picture("/img/large/card/special/special2.png"), new Picture("/img/small/card/special/special2h.png"), new Picture("/img/large/card/special/special2h.png"), 0, 0, 1, 0, 0));
        Shogun.specials.add(new Special("rice", new Picture("/img/small/card/special/special3.png"), new Picture("/img/large/card/special/special3.png"), new Picture("/img/small/card/special/special3h.png"), new Picture("/img/large/card/special/special3h.png"), 0, 0, 0, 1, 0));
        Shogun.specials.add(new Special("recruitment", new Picture("/img/small/card/special/special4.png"), new Picture("/img/large/card/special/special4.png"), new Picture("/img/small/card/special/special4h.png"), new Picture("/img/large/card/special/special4h.png"), 0, 0, 0, 0, 6));
    }

    private static void addProvince(String name, Map<String, Province> neighbours) {
        neighbours.put(name, Shogun.getProvince(name));
    }
}
